### ISSUE TITLE
Type error inside handler_writes when running in master

### ISSUE THREAD

**Issue by gbaraldi** [onetonfoot/Bonsai.jl#26]
PkgEval found this error. https://github.com/JuliaLang/julia/issues/47267 was opened, but since this touches a bunch of the julia internals I believe it makes more sense here.
To reproduce use a recent master and
```julia
using Bonsai
function g(stream)
           Bonsai.write(stream, Body("ok"), Bonsai.Status(201))
       end
Bonsai.handler_writes(g)
```

**Comment by onetonfoot** [comment]
Hi, I'm unable to reproduce running v1.8.2

![image](https://user-images.githubusercontent.com/22117475/198186362-4457859f-672c-48b0-ac01-89aa8bf6c8b3.png)

If this is still an issue on the 1.9 release I'll look into fixing it, thanks for the issue

**Comment by onetonfoot** [comment]
Seems to be a non issue on julia 1.9, although JET.jl rapid development has been breaking versions so for now we will lock to a specific version in Compat
